# Generated by Django 3.1.2 on 2020-12-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('patricipant_count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContestUser',
            fields=[
                ('perf_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('net_score', models.IntegerField(blank=True, null=True)),
                ('del_rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contest_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('problem_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('testcases', models.TextField(blank=True, null=True)),
                ('no_subs', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatedUsers',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('pdirec', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rated_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=16)),
                ('verdict', models.CharField(max_length=16)),
                ('score', models.IntegerField()),
                ('time_of_submission', models.DateTimeField()),
                ('contest_submission', models.BooleanField()),
            ],
            options={
                'db_table': 'submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(blank=True, null=True)),
                ('filepath', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_files',
                'managed': False,
            },
        ),
    ]
