# Generated by Django 3.1.4 on 2020-12-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blog_contest_contestuser_problems_ratedusers_submissions_userfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={},
        ),
    ]
