# Generated by Django 3.1.4 on 2020-12-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201206_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.blog'),
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='isRunning',
            field=models.BooleanField(default=True),
        ),
    ]
