# Generated by Django 3.1.2 on 2020-12-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201207_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFiles',
        ),
    ]
