# Generated by Django 3.1.4 on 2020-12-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201206_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='blog',
            new_name='blog_id',
        ),
    ]
