# Generated by Django 3.1.4 on 2020-12-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201206_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='isRunning',
        ),
    ]
