# Generated by Django 3.1.4 on 2020-12-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201206_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ContestUser',
        ),
        migrations.DeleteModel(
            name='Problems',
        ),
        migrations.DeleteModel(
            name='RatedUsers',
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
