language: node_js
node_js:
  - "node"

services:
  - postgresql
addons: 
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13

install:
  - npm install

env:
  global:
    - PGPORT=5433
    - DB_NAME=ocde
    - DB_USER=postgres
  before_script:
    - psql --command="CREATE USER ${DB_USER}"
    - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"

script:
  - npm run test