# Generated by Django 3.1.4 on 2020-12-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('problem', models.TextField()),
                ('input', models.FileField(upload_to='')),
                ('output', models.FileField(upload_to='')),
            ],
        ),
    ]
