# Generated by Django 3.1.4 on 2020-12-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='My Contest', max_length=64)),
                ('problem', models.TextField(default='My Problem Statement')),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('input', models.FileField(upload_to='testcases/inputs/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.IntegerField>/')),
                ('output', models.FileField(upload_to='testcases/outputs/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.IntegerField>/')),
                ('contest', models.ForeignKey(db_column='contest', on_delete=django.db.models.deletion.DO_NOTHING, to='compe.contest')),
            ],
        ),
    ]
