# Generated by Django 3.1.4 on 2020-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='output',
            field=models.FileField(upload_to='contests/<django.db.models.fields.AutoField>/'),
        ),
    ]
