# Generated by Django 3.1.4 on 2020-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compe', '0002_auto_20201207_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='input',
            field=models.FileField(upload_to='contests/{}/out/'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='output',
            field=models.FileField(upload_to='contests/<django.db.models.fields.AutoField>/out/'),
        ),
    ]
