# Generated by Django 3.1.4 on 2020-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compe', '0003_auto_20201207_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='input',
            field=models.FileField(upload_to='contests/{}/in/'),
        ),
    ]
