# Generated by Django 3.1.2 on 2020-12-07 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201207_2016'),
        ('compe', '0006_auto_20201207_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='endtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contest',
            name='starttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='ContestUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submittime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('points', models.IntegerField()),
                ('compe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compe.contest')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.authuser')),
            ],
        ),
    ]
