# Generated by Django 3.1.2 on 2020-12-07 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compe', '0007_auto_20201207_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='endtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contest',
            name='starttime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contestuser',
            name='submittime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
