# Generated by Django 3.1.2 on 2020-12-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compe', '0008_auto_20201207_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestuser',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='pointstable',
            name='userId',
        ),
        migrations.AddField(
            model_name='contestuser',
            name='username',
            field=models.CharField(default='.', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointstable',
            name='username',
            field=models.CharField(default='.', max_length=64),
            preserve_default=False,
        ),
    ]
