# Generated by Django 3.1.2 on 2020-12-07 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compe', '0009_auto_20201207_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='endtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contest',
            name='starttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contestuser',
            name='submittime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
