# Generated by Django 3.1.4 on 2020-12-08 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compe', '0010_auto_20201207_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contest',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contestuser',
            name='submittime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
